version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: mssqldb
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'p@ssword12345!'

    ports:
      - 1433:1433
